2024-02-02 20:27:11.570 | INFO     | routers.user:create_user:30 - 创建用户
2024-02-02 20:27:56.788 | INFO     | routers.user:create_user:30 - 创建用户
2024-02-02 20:30:20.454 | INFO     | routers.user:create_user:30 - 创建用户
2024-02-02 20:30:20.833 | ERROR    | routers.user:create_user:52 - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):

  File "E:\python\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002A6C7B46EF0>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002A6C7B46C20>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(asyncio_0, started 9408)>
    │    │        │    └ (<weakref at 0x000002A6CBBA87C0; to 'ThreadPoolExecutor' at 0x000002A6CBB4F7C0>, <_queue.SimpleQueue object at 0x000002A6CBBD...
    │    │        └ <Thread(asyncio_0, started 9408)>
    │    └ <function _worker at 0x000002A6CBB1BC70>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000002A6CBB1BD90>
    └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB94160>

  File "E:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB94160>
             │    │   │    └ (functools.partial(<function create_user at 0x000002A6CB8E1990>, db=<sqlalchemy.orm.session.Session object at 0x000002A6CBB94...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB94160>
             │    └ <built-in method run of _contextvars.Context object at 0x000002A6CBBA00C0>
             └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB94160>

> File "E:\网站\web\web\fastapi-backend\pythonProject\routers\user.py", line 48, in create_user
    user = db_create_user(db=db, user=user)
           │                 │        └ UserCreate(username='luggggggg', password='$2b$12$j0Wr8nVnnWRdw2G1pgCKru3erUnv4Kty0KhaDZdu6jBaMxW/8Yb/S', role='学生', jobnum=0...
           │                 └ <sqlalchemy.orm.session.Session object at 0x000002A6CBB94A60>
           └ <function db_create_user at 0x000002A6CB5391B0>

  File "E:\网站\web\web\fastapi-backend\pythonProject\models\crud.py", line 24, in db_create_user
    db_user.role = roles.id
    │       │      └ None
    │       └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x000002A6CB4FE750>
    └ <models.models.User object at 0x000002A6CBB97850>

AttributeError: 'NoneType' object has no attribute 'id'
2024-02-02 20:30:32.652 | INFO     | routers.user:create_user:30 - 创建用户
2024-02-02 20:30:32.910 | ERROR    | routers.user:create_user:52 - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):

  File "E:\python\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002A6C7B46EF0>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002A6C7B46C20>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(asyncio_0, started 9408)>
    │    │        │    └ (<weakref at 0x000002A6CBBA87C0; to 'ThreadPoolExecutor' at 0x000002A6CBB4F7C0>, <_queue.SimpleQueue object at 0x000002A6CBBD...
    │    │        └ <Thread(asyncio_0, started 9408)>
    │    └ <function _worker at 0x000002A6CBB1BC70>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000002A6CBB1BD90>
    └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB4FDF0>

  File "E:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB4FDF0>
             │    │   │    └ (functools.partial(<function create_user at 0x000002A6CB8E1990>, db=<sqlalchemy.orm.session.Session object at 0x000002A6CBB4F...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB4FDF0>
             │    └ <built-in method run of _contextvars.Context object at 0x000002A6CBB531C0>
             └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB4FDF0>

> File "E:\网站\web\web\fastapi-backend\pythonProject\routers\user.py", line 48, in create_user
    user = db_create_user(db=db, user=user)
           │                 │        └ UserCreate(username='luggggggg', password='$2b$12$n79GmtYrKHEE32ezYmbBquXUgrB4rWsvjKmaKq7axsQbcCtiQxMr6', role='学生', jobnum=0...
           │                 └ <sqlalchemy.orm.session.Session object at 0x000002A6CBB4FB80>
           └ <function db_create_user at 0x000002A6CB5391B0>

  File "E:\网站\web\web\fastapi-backend\pythonProject\models\crud.py", line 24, in db_create_user
    db_user.role = roles.id
    │       │      └ None
    │       └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x000002A6CB4FE750>
    └ <models.models.User object at 0x000002A6CBB4DD20>

AttributeError: 'NoneType' object has no attribute 'id'
2024-02-02 20:33:22.712 | INFO     | routers.user:create_user:30 - 创建用户
2024-02-02 20:33:23.000 | ERROR    | routers.user:create_user:52 - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):

  File "E:\python\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002A6C7B46EF0>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002A6C7B46C20>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(asyncio_0, started 9408)>
    │    │        │    └ (<weakref at 0x000002A6CBBA87C0; to 'ThreadPoolExecutor' at 0x000002A6CBB4F7C0>, <_queue.SimpleQueue object at 0x000002A6CBBD...
    │    │        └ <Thread(asyncio_0, started 9408)>
    │    └ <function _worker at 0x000002A6CBB1BC70>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000002A6CBB1BD90>
    └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB96770>

  File "E:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB96770>
             │    │   │    └ (functools.partial(<function create_user at 0x000002A6CB8E1990>, db=<sqlalchemy.orm.session.Session object at 0x000002A6CBB97...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB96770>
             │    └ <built-in method run of _contextvars.Context object at 0x000002A6CBBA2880>
             └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB96770>

> File "E:\网站\web\web\fastapi-backend\pythonProject\routers\user.py", line 48, in create_user
    user = db_create_user(db=db, user=user)
           │                 │        └ UserCreate(username='luggggggg', password='$2b$12$/sdB0yX7HKNv5hHmCwftIeLRdtpc38r/zHgrDof4YemsBHeTmka6q', role='学生', jobnum=0...
           │                 └ <sqlalchemy.orm.session.Session object at 0x000002A6CBB97700>
           └ <function db_create_user at 0x000002A6CB5391B0>

  File "E:\网站\web\web\fastapi-backend\pythonProject\models\crud.py", line 24, in db_create_user
    db_user.role = roles.id
    │       │      └ None
    │       └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x000002A6CB4FE750>
    └ <models.models.User object at 0x000002A6CBB97FD0>

AttributeError: 'NoneType' object has no attribute 'id'
2024-02-02 20:37:04.776 | INFO     | routers.user:create_user:30 - 创建用户
2024-02-02 20:37:05.032 | ERROR    | routers.user:create_user:52 - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):

  File "E:\python\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002A6C7B46EF0>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002A6C7B46C20>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(asyncio_0, started 9408)>
    │    │        │    └ (<weakref at 0x000002A6CBBA87C0; to 'ThreadPoolExecutor' at 0x000002A6CBB4F7C0>, <_queue.SimpleQueue object at 0x000002A6CBBD...
    │    │        └ <Thread(asyncio_0, started 9408)>
    │    └ <function _worker at 0x000002A6CBB1BC70>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000002A6CBB1BD90>
    └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBC801C0>

  File "E:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBC801C0>
             │    │   │    └ (functools.partial(<function create_user at 0x000002A6CB8E1990>, db=<sqlalchemy.orm.session.Session object at 0x000002A6CBB97...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBC801C0>
             │    └ <built-in method run of _contextvars.Context object at 0x000002A6CBB8A340>
             └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBC801C0>

> File "E:\网站\web\web\fastapi-backend\pythonProject\routers\user.py", line 48, in create_user
    user = db_create_user(db=db, user=user)
           │                 │        └ UserCreate(username='liwanle1i', password='$2b$12$bXAk0h2kmWbaMsWP9V3AAu2kkMMa255cMggyRWrsUp.c3UwRnLJsO', role='学生', jobnum=9...
           │                 └ <sqlalchemy.orm.session.Session object at 0x000002A6CBB97910>
           └ <function db_create_user at 0x000002A6CB5391B0>

  File "E:\网站\web\web\fastapi-backend\pythonProject\models\crud.py", line 24, in db_create_user
    db_user.role = roles.id
    │       │      └ None
    │       └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x000002A6CB4FE750>
    └ <models.models.User object at 0x000002A6CBB97A60>

AttributeError: 'NoneType' object has no attribute 'id'
2024-02-02 20:38:06.184 | INFO     | routers.user:create_user:30 - 创建用户
2024-02-02 20:38:06.442 | ERROR    | routers.user:create_user:52 - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):

  File "E:\python\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002A6C7B46EF0>
    └ <Thread(asyncio_1, started 14692)>

  File "E:\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002A6C7B46C20>
    └ <Thread(asyncio_1, started 14692)>

  File "E:\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(asyncio_1, started 14692)>
    │    │        │    └ (<weakref at 0x000002A6CBC69AD0; to 'ThreadPoolExecutor' at 0x000002A6CBB4F7C0>, <_queue.SimpleQueue object at 0x000002A6CBBD...
    │    │        └ <Thread(asyncio_1, started 14692)>
    │    └ <function _worker at 0x000002A6CBB1BC70>
    └ <Thread(asyncio_1, started 14692)>

  File "E:\python\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000002A6CBB1BD90>
    └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBC80640>

  File "E:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBC80640>
             │    │   │    └ (functools.partial(<function create_user at 0x000002A6CB8E1990>, db=<sqlalchemy.orm.session.Session object at 0x000002A6CBC81...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBC80640>
             │    └ <built-in method run of _contextvars.Context object at 0x000002A6CBC784C0>
             └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBC80640>

> File "E:\网站\web\web\fastapi-backend\pythonProject\routers\user.py", line 48, in create_user
    user = db_create_user(db=db, user=user)
           │                 │        └ UserCreate(username='liwanle1i', password='$2b$12$CFhGpnM0TJtCMVEzljjKTuzHogGbg2blSoQUzPkViyy3JXf8vEYCC', role='学生', jobnum=0...
           │                 └ <sqlalchemy.orm.session.Session object at 0x000002A6CBC81060>
           └ <function db_create_user at 0x000002A6CB5391B0>

  File "E:\网站\web\web\fastapi-backend\pythonProject\models\crud.py", line 24, in db_create_user
    db_user.role = roles.id
    │       │      └ None
    │       └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x000002A6CB4FE750>
    └ <models.models.User object at 0x000002A6CBB97040>

AttributeError: 'NoneType' object has no attribute 'id'
2024-02-02 20:38:13.785 | INFO     | routers.user:create_user:30 - 创建用户
2024-02-02 20:38:14.055 | ERROR    | routers.user:create_user:52 - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):

  File "E:\python\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002A6C7B46EF0>
    └ <Thread(asyncio_1, started 14692)>

  File "E:\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002A6C7B46C20>
    └ <Thread(asyncio_1, started 14692)>

  File "E:\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(asyncio_1, started 14692)>
    │    │        │    └ (<weakref at 0x000002A6CBC69AD0; to 'ThreadPoolExecutor' at 0x000002A6CBB4F7C0>, <_queue.SimpleQueue object at 0x000002A6CBBD...
    │    │        └ <Thread(asyncio_1, started 14692)>
    │    └ <function _worker at 0x000002A6CBB1BC70>
    └ <Thread(asyncio_1, started 14692)>

  File "E:\python\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000002A6CBB1BD90>
    └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBC81810>

  File "E:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBC81810>
             │    │   │    └ (functools.partial(<function create_user at 0x000002A6CB8E1990>, db=<sqlalchemy.orm.session.Session object at 0x000002A6CBC81...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBC81810>
             │    └ <built-in method run of _contextvars.Context object at 0x000002A6CBC73CC0>
             └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBC81810>

> File "E:\网站\web\web\fastapi-backend\pythonProject\routers\user.py", line 48, in create_user
    user = db_create_user(db=db, user=user)
           │                 │        └ UserCreate(username='liwanle1i', password='$2b$12$PoD2gMY64FSLdyusaFUsV.Q7RKUqg9ZNFpKMAwG/ErmjvcSxkSyrW', role='学生', jobnum=N...
           │                 └ <sqlalchemy.orm.session.Session object at 0x000002A6CBC81C60>
           └ <function db_create_user at 0x000002A6CB5391B0>

  File "E:\网站\web\web\fastapi-backend\pythonProject\models\crud.py", line 24, in db_create_user
    db_user.role = roles.id
    │       │      └ None
    │       └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x000002A6CB4FE750>
    └ <models.models.User object at 0x000002A6CBB96710>

AttributeError: 'NoneType' object has no attribute 'id'
2024-02-02 20:45:15.252 | INFO     | routers.user:create_user:30 - 创建用户
2024-02-02 20:45:15.507 | ERROR    | routers.user:create_user:52 - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):

  File "E:\python\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002A6C7B46EF0>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002A6C7B46C20>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(asyncio_0, started 9408)>
    │    │        │    └ (<weakref at 0x000002A6CBBA87C0; to 'ThreadPoolExecutor' at 0x000002A6CBB4F7C0>, <_queue.SimpleQueue object at 0x000002A6CBBD...
    │    │        └ <Thread(asyncio_0, started 9408)>
    │    └ <function _worker at 0x000002A6CBB1BC70>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000002A6CBB1BD90>
    └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB95F00>

  File "E:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB95F00>
             │    │   │    └ (functools.partial(<function create_user at 0x000002A6CB8E1990>, db=<sqlalchemy.orm.session.Session object at 0x000002A6CBB95...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB95F00>
             │    └ <built-in method run of _contextvars.Context object at 0x000002A6CBB513C0>
             └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB95F00>

> File "E:\网站\web\web\fastapi-backend\pythonProject\routers\user.py", line 48, in create_user
    user = db_create_user(db=db, user=user)
           │                 │        └ UserCreate(username='liwanle1i', password='$2b$12$jzwitB9ygyfKK3a9Ei/BtODnS6DEp96T/RZN4AU1x5l4l0t7GqLfO', role='学生', jobnum=0...
           │                 └ <sqlalchemy.orm.session.Session object at 0x000002A6CBB95720>
           └ <function db_create_user at 0x000002A6CB5391B0>

  File "E:\网站\web\web\fastapi-backend\pythonProject\models\crud.py", line 24, in db_create_user
    db_user.role = roles.id
    │       │      └ None
    │       └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x000002A6CB4FE750>
    └ <models.models.User object at 0x000002A6CBB94A00>

AttributeError: 'NoneType' object has no attribute 'id'
2024-02-02 20:46:17.203 | INFO     | routers.user:create_user:30 - 创建用户
2024-02-02 20:46:17.485 | ERROR    | routers.user:create_user:52 - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):

  File "E:\python\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002A6C7B46EF0>
    └ <Thread(asyncio_1, started 14692)>

  File "E:\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002A6C7B46C20>
    └ <Thread(asyncio_1, started 14692)>

  File "E:\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(asyncio_1, started 14692)>
    │    │        │    └ (<weakref at 0x000002A6CBC69AD0; to 'ThreadPoolExecutor' at 0x000002A6CBB4F7C0>, <_queue.SimpleQueue object at 0x000002A6CBBD...
    │    │        └ <Thread(asyncio_1, started 14692)>
    │    └ <function _worker at 0x000002A6CBB1BC70>
    └ <Thread(asyncio_1, started 14692)>

  File "E:\python\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000002A6CBB1BD90>
    └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB4E050>

  File "E:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB4E050>
             │    │   │    └ (functools.partial(<function create_user at 0x000002A6CB8E1990>, db=<sqlalchemy.orm.session.Session object at 0x000002A6CBB4F...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB4E050>
             │    └ <built-in method run of _contextvars.Context object at 0x000002A6CBBDB280>
             └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB4E050>

> File "E:\网站\web\web\fastapi-backend\pythonProject\routers\user.py", line 48, in create_user
    user = db_create_user(db=db, user=user)
           │                 │        └ UserCreate(username='liwanle1i', password='$2b$12$ezub7ciETC8URwtOsLjvvu4sFEg8gQC7txTXq7ICjWrRqjwNvlYXO', role='学生', jobnum=0...
           │                 └ <sqlalchemy.orm.session.Session object at 0x000002A6CBB4FEE0>
           └ <function db_create_user at 0x000002A6CB5391B0>

  File "E:\网站\web\web\fastapi-backend\pythonProject\models\crud.py", line 24, in db_create_user
    db_user.role = roles.id
    │       │      └ None
    │       └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x000002A6CB4FE750>
    └ <models.models.User object at 0x000002A6CBB4DEA0>

AttributeError: 'NoneType' object has no attribute 'id'
2024-02-02 21:07:19.071 | INFO     | routers.user:create_user:30 - 创建用户
2024-02-02 21:07:19.346 | ERROR    | routers.user:create_user:52 - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):

  File "E:\python\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002A6C7B46EF0>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002A6C7B46C20>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(asyncio_0, started 9408)>
    │    │        │    └ (<weakref at 0x000002A6CBBA87C0; to 'ThreadPoolExecutor' at 0x000002A6CBB4F7C0>, <_queue.SimpleQueue object at 0x000002A6CBBD...
    │    │        └ <Thread(asyncio_0, started 9408)>
    │    └ <function _worker at 0x000002A6CBB1BC70>
    └ <Thread(asyncio_0, started 9408)>

  File "E:\python\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000002A6CBB1BD90>
    └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB94FD0>

  File "E:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB94FD0>
             │    │   │    └ (functools.partial(<function create_user at 0x000002A6CB8E1990>, db=<sqlalchemy.orm.session.Session object at 0x000002A6CBC81...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB94FD0>
             │    └ <built-in method run of _contextvars.Context object at 0x000002A6CB5AB000>
             └ <concurrent.futures.thread._WorkItem object at 0x000002A6CBB94FD0>

> File "E:\网站\web\web\fastapi-backend\pythonProject\routers\user.py", line 48, in create_user
    user = db_create_user(db=db, user=user)
           │                 │        └ UserCreate(username='liwanle1i', password='$2b$12$9tbdHGvQASl4N68y6TZ9tOtEzZU4CYjJao0nsVOLZIplaua4A.zQK', role='学生', jobnum=0...
           │                 └ <sqlalchemy.orm.session.Session object at 0x000002A6CBC81A50>
           └ <function db_create_user at 0x000002A6CB5391B0>

  File "E:\网站\web\web\fastapi-backend\pythonProject\models\crud.py", line 24, in db_create_user
    db_user.role = roles.id
    │       │      └ None
    │       └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x000002A6CB4FE750>
    └ <models.models.User object at 0x000002A6CBB4EDA0>

AttributeError: 'NoneType' object has no attribute 'id'
2024-02-02 21:13:47.545 | INFO     | routers.user:create_user:30 - 创建用户
2024-02-02 21:13:48.318 | SUCCESS  | routers.user:create_user:49 - 创建用户成功
2024-02-02 22:30:35.725 | INFO     | routers.user:login:92 - login：1不存在
2024-02-02 23:03:31.209 | INFO     | routers.user:login:92 - login：asdf不存在
2024-02-02 23:46:29.478 | INFO     | routers.user:login:92 - login：1不存在
2024-02-02 23:46:38.958 | INFO     | routers.user:login:92 - login：1不存在
